contentdir = "content"
destination = "/home/g/www/gradycongdon.github.io"
theme = "cocoa"
baseurl = "https://gradycongdon.github.io"
title = "glog"
languageCode = "en-us"
canonifyurls = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
